x86/microcode: Place siblings in NMI loop while update in progress
Microcode updates affect the state of the running CPU. In the case of
hyper-threads, the thread initiating the update is in a known state
(performing wrmsr 0x79), but its HT sibling can be executing arbitrary
instructions.

Some of these arbitrary instructions might be affected by the microcode
patch. If an instruction is affected, it can encounter odd, undefined
behavior like a #GP for no apparent reason or even cause system hangs.

To reduce the chance of hitting one of these arbitrary instructions, the
kernel can reduce the kind of code that might be running during an update.
Spinning in a stop_machine() handler with interrupts off will prevent
user space, normal interrupts and sane exception from running.

However, that still leaves the NMI entry code and handlers.

== Solution: NMI prevention during update ==

Register an NMI handler before the stop_machine() rendezvous. Place the
handler as the first entry in the handler list. Then, have the siblings
kick themselves into NMI by doing a self NMI IPI.

The next NMI will run the newly-registered handler and can block any new
NMIs from coming in [1]

The handler does two things:

- Informs the primary thread that it has entered the NMI handler. Only
  after all siblings of a core have entered NMI, the primary proceeds
  with wrmsr to update microcode.
- Secondary threads spin in NMI until the primary thread has completed
  the wrmsr and informs the sibling to release itself from NMI.

Also an important thing to remember is the microcode requests for exclusive
access to the core before performing an update. This effectively pulls the
sibling into microcode control until the wrmsr has released exclusive
access. Since the sibling is not executing any instructions while the
wrmsr completes, no other exceptions will surface on the sibling CPU.

Breakpoints can be another source that can lead do taking exceptions. But
on NMI entry, the kernel seems to be save/clear/restore the breakpoint
control register (DR7). local_db_save() and local_db_restore(). This
effectively eliminates any breakpoints leading the sibling into
uncontrolled execution.

Place all secondary threads of a core in NMI until the primary thread
completes the microcode update. Then release the secondary threads.

[1] This "new NMI blocking" behavior is not strictly true for all cases,
such as when CONFIG_DEBUG_ENTRY is enabled. hold_sibling_in_nmi() is called
earlier before NMI's are re-enabled for CONFIG_DEBUG_ENTRY purposes.

Suggested-by: Thomas Gleixner <tglx@linutronix.de>
Signed-off-by: Ashok Raj <ashok.raj@intel.com>
Cc: LKML <linux-kernel@vger.kernel.org>
Cc: x86 <x86@kernel.org>
Cc: Tony Luck <tony.luck@intel.com>
Cc: Dave Hansen <dave.hansen@intel.com>
Cc: Alison Schofield <alison.schofield@intel.com>
Cc: Reinette Chatre <reinette.chatre@intel.com>
Cc: Thomas Gleixner <tglx@linutronix.de>
Cc: Stefan Talpalaru <stefantalpalaru@yahoo.com>
Cc: Tom Lendacky <thomas.lendacky@amd.com>
Cc: David Woodhouse <dwmw2@infradead.org>
Cc: Benjamin Herrenschmidt <benh@kernel.crashing.org>
---
Dave Hansen
- Lots of commit log updates to make it more legible.
lkp bot
- Fix UP compile issues
  Undefined reference to apic